const listNode=document.querySelector('#list');
const reader=document.querySelector('#reader');
const search=document.querySelector('#search');
const total=document.querySelector('#total');
let manifest=[];let documents=new Map();let selected='';
const fmt=value=>new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'short',day:'numeric'}).format(new Date(value));
const short=value=>(value||'').replace(/\s+/g,' ').trim().slice(0,86);
function make(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node}
function renderList(items){listNode.replaceChildren();if(!items.length){listNode.append(make('div','none','没有匹配的归档'));return}for(const item of items){const link=make('a','entry'+(item.id===selected?' active':''));link.href=`?id=${encodeURIComponent(item.id)}`;link.dataset.id=item.id;link.append(make('strong','entry-title',item.title),make('span','entry-preview',item.preview||'逐字保存的公开对话'));const foot=make('span','entry-foot');foot.append(make('span','',`${item.message_count} MESSAGES`),make('span','',fmt(item.updated_at)));link.append(foot);link.addEventListener('click',event=>{event.preventDefault();open(item.id,true)});listNode.append(link)}}
function render(doc){document.title=`${doc.title} · Dialogue Vault`;reader.replaceChildren();const hero=make('header','hero');hero.append(make('div','eyebrow','Conversation archive'),make('h2','',doc.title));const meta=make('div','meta');meta.append(make('span','',`${doc.message_count} 条消息`),make('span','',`更新于 ${fmt(doc.updated_at)}`));const share=make('button','share','复制本页链接');share.addEventListener('click',async()=>{await navigator.clipboard.writeText(location.href);share.textContent='链接已复制';setTimeout(()=>share.textContent='复制本页链接',1400)});meta.append(share);hero.append(meta);reader.append(hero);const transcript=make('article','transcript');doc.messages.forEach((item,index)=>{const section=make('section',`message ${item.role}`);const avatar=make('div','avatar',item.role==='user'?'YOU':'AI');const content=make('div','content');const head=make('div','message-head');head.append(make('strong','role',item.role==='user'?'用户':'AI'),make('span','number',`#${String(index+1).padStart(2,'0')}`));const copy=make('button','copy-message','复制原文');copy.addEventListener('click',async()=>{await navigator.clipboard.writeText(item.text);copy.textContent='已复制';setTimeout(()=>copy.textContent='复制原文',1200)});head.append(copy);const body=make('div','body');const text=make('pre','',item.text);text.dataset.message=String(index+1);body.append(text);content.append(head,body);section.append(avatar,content);transcript.append(section)});reader.append(transcript);const integrity=make('footer','integrity');integrity.append(make('span','integrity-dot'),make('span','',`VERIFIED ORIGINAL · SHA-256 ${doc.dialogue_sha256.slice(0,12)}…`));reader.append(integrity)}
async function open(id,push=false){if(!id){reader.innerHTML='<div class="empty">还没有公开归档。</div>';return}selected=id;if(push)history.pushState({id},'',`?id=${encodeURIComponent(id)}`);renderList(manifest);reader.innerHTML='<div class="skeleton"></div>';let doc=documents.get(id);if(!doc){const response=await fetch(`conversations/${encodeURIComponent(id)}.json`);if(!response.ok)throw new Error(`HTTP ${response.status}`);doc=await response.json();documents.set(id,doc)}render(doc)}
async function filter(){const query=search.value.trim().toLocaleLowerCase();if(!query){renderList(manifest);return}const hits=[];for(const item of manifest){if(`${item.title} ${item.preview||''}`.toLocaleLowerCase().includes(query)){hits.push(item);continue}let doc=documents.get(item.id);if(!doc){try{doc=await fetch(`conversations/${encodeURIComponent(item.id)}.json`).then(r=>r.json());documents.set(item.id,doc)}catch{continue}}if(doc.messages.some(message=>message.text.toLocaleLowerCase().includes(query)))hits.push(item)}renderList(hits)}
let searchTimer;search.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(filter,160)});addEventListener('popstate',()=>open(new URLSearchParams(location.search).get('id')||manifest[0]?.id));
(async()=>{try{const response=await fetch('conversations/index.json',{cache:'no-store'});manifest=await response.json();total.textContent=String(manifest.length).padStart(2,'0');const requested=new URLSearchParams(location.search).get('id');await open(manifest.some(item=>item.id===requested)?requested:manifest[0]?.id)}catch(error){reader.innerHTML='<div class="empty">归档暂时无法载入。</div>';console.error(error)}})();
