const listNode=document.querySelector('#list');
const reader=document.querySelector('#reader');
const search=document.querySelector('#search');
let manifest=[];let documents=new Map();let selected='';
const date=value=>new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
function list(items){listNode.replaceChildren();if(!items.length){const n=document.createElement('div');n.className='none';n.textContent='没有匹配的归档';listNode.append(n);return}for(const item of items){const a=document.createElement('a');a.className='entry'+(item.id===selected?' active':'');a.href=`?id=${encodeURIComponent(item.id)}`;a.dataset.id=item.id;const title=document.createElement('strong');title.textContent=item.title;const meta=document.createElement('small');meta.textContent=`${item.message_count} 条消息 · ${date(item.updated_at)}`;a.append(title,meta);a.addEventListener('click',event=>{event.preventDefault();open(item.id,true)});listNode.append(a)}}
function render(doc){document.title=`${doc.title} · Dialogue Vault`;reader.replaceChildren();const hero=document.createElement('header');hero.className='hero';const h=document.createElement('h2');h.textContent=doc.title;const meta=document.createElement('div');meta.className='meta';const count=document.createElement('span');count.textContent=`${doc.message_count} 条消息`;const updated=document.createElement('span');updated.textContent=`更新于 ${date(doc.updated_at)}`;const share=document.createElement('a');share.className='share';share.href=`?id=${encodeURIComponent(doc.id)}`;share.textContent='复制此页链接';share.addEventListener('click',async event=>{event.preventDefault();await navigator.clipboard.writeText(share.href);share.textContent='已复制';setTimeout(()=>share.textContent='复制此页链接',1400)});meta.append(count,updated,share);hero.append(h,meta);reader.append(hero);doc.messages.forEach((item,index)=>{const section=document.createElement('section');section.className=`message ${item.role}`;const role=document.createElement('div');role.className='role';role.textContent=item.role==='user'?'You':'AI';const bubble=document.createElement('div');bubble.className='bubble';const text=document.createElement('pre');text.textContent=item.text;text.dataset.message=String(index+1);bubble.append(text);section.append(role,bubble);reader.append(section)})}
async function open(id,push=false){selected=id;if(push)history.pushState({id},'',`?id=${encodeURIComponent(id)}`);list(manifest);reader.innerHTML='<div class="empty">正在载入对话…</div>';let doc=documents.get(id);if(!doc){const response=await fetch(`conversations/${encodeURIComponent(id)}.json`);if(!response.ok)throw new Error(`HTTP ${response.status}`);doc=await response.json();documents.set(id,doc)}render(doc)}
search.addEventListener('input',()=>{const q=search.value.trim().toLocaleLowerCase();list(manifest.filter(item=>item.title.toLocaleLowerCase().includes(q)))});
addEventListener('popstate',()=>open(new URLSearchParams(location.search).get('id')||manifest[0]?.id));
(async()=>{try{const response=await fetch('conversations/index.json',{cache:'no-store'});manifest=await response.json();const requested=new URLSearchParams(location.search).get('id');await open(manifest.some(item=>item.id===requested)?requested:manifest[0]?.id)}catch(error){reader.innerHTML='<div class="empty">归档暂时无法载入。</div>';console.error(error)}})();
